### PR TITLE
Loads IANA registry and use it for validation and canonicalization

### PR DESCRIPTION
**Pull request by Tpt**
Updates `LanguageTag::validate` and `LanguageTag::canonicalize` to use it.

`LanguageTag::canonicalize` returns a validation error if there is no simple way of returning a "canonical version" of the language tag. For example, it does not fail if the region is not in the registry but fails if there are multiple language extensions because there is no proper way to choose which one to use to update the primary language.

To update the IANA registry local version run `python3 scripts/update_from_iana_subtag_registery.py && cargo fmt`

### CODE REVIEW

**Comment by Tpt** [comment]
Benchmarks from PR #15:
master:
test canonicalize_tags      ... bench:      15,937 ns/iter (+/- 3,803) = 39 MB/s
test parse_well_formed_tags ... bench:       9,411 ns/iter (+/- 1,300) = 62 MB/s
test validate_tags          ... bench:       1,501 ns/iter (+/- 124) = 415 MB/s

this PR:
test canonicalize_tags      ... bench:      33,916 ns/iter (+/- 1,080) = 18 MB/s
test parse_well_formed_tags ... bench:       8,664 ns/iter (+/- 279) = 67 MB/s
test validate_tags          ... bench:      20,921 ns/iter (+/- 865) = 29 MB/s

This is a significant slowdown but many more features are now implemented

**Comment by pyfisch** [comment]
The registry file is *huge*. How big is the resulting executable?

**Comment by Tpt** [comment]
The *.rlib file is 8MB but release executables are much smaller (~4MB for the benchmarks)

**Comment by pyfisch** [comment]
The release tests after running strip have a size of 1.5M (before 698 kB). I've decided for myself that this is too much and experimented a bit with more efficient storage. I will publish a PR for you to review soon. With this optimization the executable should be around 900 kB and the benchmarks will be a bit worse.

**Comment by Tpt** [comment]
Great! Thanks!

**Comment by pyfisch** [comment]
Hi,

I've coded myself a bit into a corner. While I got the executable size down the performance is also reduced quite a bit. The main problem is that each needs a pointer and a length (16 bytes) and therefore a `LanguageRecord` has a size of 64 bytes on 64 bit machines (the options are free). Additionally the string data needs to be stored. On the other hand the binary lookup by tag should be fast.

```rust
pub struct LanguageRecord {
    pub subtag: &'static str,
    pub preferred_value: Option<&'static str>,
    pub suppress_script: Option<&'static str>,
    pub macrolanguage: Option<&'static str>
}
```

**Comment by Tpt** [comment]
Thanks!

There is probably a way to improve the storage space by avoiding `&'static str`. For most of the record types, the subtag size is fixed so we could use a [u8; MAX_SIZE] as container. It may require some unsafe code to avoid a lot of UTF-8 validity checking but it could be much smaller and hopefully faster because of less indirections.

For example, `LanguageRecord` would be:

```rust
pub struct LanguageRecord {
    pub subtag: [u8; 3], // The last byte could be \0 for tags of length 2 like "en"
    pub preferred_value: Option<[u8; 3]>,
    pub suppress_script: Option<[u8; 4]>,
    pub macrolanguage: Option<[u8; 2]>
}

```

We may also experiment `repr(packed)` on it.

**Comment by pyfisch** [comment]
Sound good. Yeah it probably a good idea to store the fixed fields in arrays. Is there a way to get a 'static str from an array? (How does the borrowing work?)

Do you want to write a PR that improves storage space?

**Comment by Tpt** [comment]
> Is there a way to get a 'static str from an array?

Yes, the good function is [str::from_utf8()](https://doc.rust-lang.org/std/str/fn.from_utf8.html) that takes a `&'a [u8]` as input and give back a `&'a str`. The last example of the doc is exactly what we are looking for I think.

I could try to work on it but if you whish to do so, feel free to do it.

**Comment by pyfisch** [comment]
Ah I see why I can't use `'static str` with LanguageRecord but the `&'a str` you suggest is good enough.

> I could try to work on it but if you whish to do so, feel free to do it.

I would be great if you work on it.

**Pull request merged**
